### ISSUE TITLE
Restore ZIP folder for schema releases on WMO website

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm-modelling#21]
Received a comment from a user who was confused about where to obtain the authoritative IWXXM schema releases. This repository offers zip'ped files for downloading as a convenience but these files are not authoritative since the master branch is not always in a finalized state.  Even tagged releases in this repository are not considered official (correct?).

Releases prior to IWXXM version 3.0 provided zip'ped files for [downloading](https://schemas.wmo.int/iwxxm/2.1/zip/) on the WMO web site.  Subsequent releases do not have a zip directory. 

Proposed enhancments would be:

- Provide zip folders with zip'ped schema packages on the WMO web site for future releases of IWXXM;
- If possible, disable GitHub from providing zip'ped files for downloading from this repository.

**Comment by amilan17** [comment]
@mgoberfield Thank you for the recommendation. It is certainly possible to provide zipped directories for all versions. I don't think I can restrict downloading from GitHub, but I can add some text describing where to get the official copies.

**Comment by mgoberfield** [comment]
Thanks Anna!

**Comment by blchoy** [comment]
Historically, zip files containing schemas, examples, models, are provided on schemas.wmo.int for each published version.  This was stopped since version 3.0 as the team at that time thought that this could be easily retrieved (note that the zip files on schemas.wmo.int has a different directory structure) from the zipped GitHub repository of individual releases.

We need to answer two questions:
1. Are we going to provide zip files on schemas, examples, models, etc. similar to what we have done prior to version 3.0 to facilitate their use by repackaging the files on GitHub?  Is there any possibility to simply the content of these zip files?
2. Where should we put these files?  Files could be attached when we prepare a GitHub release.  We could also put them onto schemas.wmo.int as we used to, or on the WMO Community Website in which now they use SharePoint for file sharing, either way could be considered authentic.

**Comment by mgoberfield** [comment]
As reported to me, the IWXXM consumer just wanted to get all of the schemas, schematron and RDF files with one download to perform XML validation. There was no mention of needing the example or documentation files. For XML validation, the approximate number is around 30 files and the count will grow larger over time with each new release.

**Comment by blchoy** [comment]
> As reported to me, the IWXXM consumer just wanted to get all of the schemas, schematron and RDF files with one download to perform XML validation. There was no mention of needing the example or documentation files. For XML validation, the approximate number is around 30 files and the count will grow larger over time with each new release.

OK.  Let's create a minimal zip file for such purpose.
